version: '3.8'

services:
  regalhub:
    build:
      context: .
      dockerfile: Dockerfile
      # Add build args for faster builds
      args:
        - NODE_ENV=production
    container_name: regalhub-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Add health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3